services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 3001:3000
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
  db:
    image: postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password